### ISSUE TITLE
How do we use the Bearer token?

### ISSUE THREAD

**Issue by fayazara** [HunterLarco/twitter-v2#32]
I just want to get a tweet as a json from it's id. 

I tried the following, but it won't work, I get this error.
```
const express = require("express");
const app = express();
const Twitter = require("twitter-v2");
const axios = require("axios");

var client = new Twitter({
  consumer_key: process.env.TWITTER_CONSUMER_KEY,
  consumer_secret: process.env.TWITTER_CONSUMER_SECRET,
  bearer_token: process.env.TWITTER_BEARER_TOKEN
});

app.get("/", async (request, response) => {
  const { data } = await client.get("tweets", { ids: "1343068487405596672" });
  response.send(data);
});

const listener = app.listen(process.env.PORT, () => {
  console.log("Your app is listening on port " + listener.address().port);
});
```
```
(node:3865) UnhandledPromiseRejectionWarning: Error: Client Forbidden: When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer app that is attached to a Project. You can create a project via the developer portal.
    at Function.module.exports.fromJson (/rbd/pnpm-volume/9f6f5ef1-e8fd-449a-bc06-21e1a90a3bac/node_modules/.registry.npmjs.org/twitter-v2/1.0.0/node_modules/twitter-v2/src/TwitterError.js:29:12)
    at Twitter.get (/rbd/pnpm-volume/9f6f5ef1-e8fd-449a-bc06-21e1a90a3bac/node_modules/.registry.npmjs.org/twitter-v2/1.0.0/node_modules/twitter-v2/src/twitter.js:46:32)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
at async /app/server.js:13:20
(node:3865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

**Comment by HunterLarco** [comment]
I suspect that this error is occurring because of invalid Twitter credentials. Can you confirm that your application is correctly constructing the `Twitter` object with valid credentials?

**Comment by wrsulliv** [comment]
@fayazara I was having this error as well.  For me, removing the word and space ("Bearer ") from the "bearer_token" string solved the problem.

**Comment by HunterLarco** [comment]
Interesting. See #35 which should automatically normalize the bearer token eliminating this problem in the future =)
